inherit_from: .rubocop_todo.yml

# inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineLength:
  Max: 100
  Severity: refactor

Metrics/BlockLength:
  CountAsOne: ["hash", "array", "heredoc"]
  Exclude:
    - "spec/**/*"

Metrics/ModuleLength:
  CountAsOne: ["hash", "array", "heredoc"]
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  CountAsOne: ["hash", "array", "heredoc"]
  Exclude:
    - "db/migrate/**/*"

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - "Gemfile"

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Rails/NotNullColumn:
  Enabled: false
