services:
  postgres:
    image: postgres:12.7-alpine
    env_file:
      - ".env.${RAILS_ENV:-development}"
      - .env.docker
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    volumes:
      - redis:/data
    command: >
      sh -c "echo 'Starting redis server...' &&
             redis-server"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: "development"
      NODE_ENV: "development"
    env_file:
      - ".env.${RAILS_ENV:-development}"
      - .env.docker
    ports:
      - 5000:3000
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    tmpfs:
      - /tmp/pids/
    tty: true
    stdin_open: true

volumes:
  postgres: {}
  redis: {}
