name: Pronto
on: [pull_request, main]
jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Install Gnar Style
        run: gem install gnar-style

      - name: Pronto Ruby
        uses: AdWerx/pronto-ruby@v4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: origin/main
          runners: rubocop rails_schema brakeman bundler_audit rails_best_practices fasterer
