name: Pronto
on: [pull_request]
jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch origin main --depth=1

      - name: Pronto Ruby
        uses: AdWerx/pronto-ruby@v4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GNARBOT_TOKEN }}
        with:
          target: origin/main
          runners: rubocop rails_schema brakeman bundler_audit rails_best_practices fasterer
