name: Gnarbot
on:
  pull_request:

jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: HeRoMo/pronto-action@v1.56.0
        with:
          github_token: ${{ secrets.GNARBOT_TOKEN }}
          runner: rubocop brakeman rails_best_practices
          formatters: text github_status github_pr_review
